# Generated by Django 5.2.1 on 2026-01-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additional_settings', '0008_labour_material_truck_hub_code'),
        ('quotation', '0007_quotation_additional_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('move_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='quotation.quotation')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_bookings', to='additional_settings.manpower')),
            ],
        ),
        migrations.CreateModel(
            name='BookingLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='bookings.booking')),
                ('labour_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additional_settings.labour')),
            ],
        ),
        migrations.CreateModel(
            name='BookingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='bookings.booking')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additional_settings.material')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='bookings.booking')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additional_settings.truck')),
            ],
        ),
    ]
