# Generated by Django 5.2.1 on 2026-01-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0009_alter_labour_name_alter_material_name_and_more'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookinglabour',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='bookinglabour',
            name='labour_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additional_settings.labour'),
        ),
        migrations.AlterField(
            model_name='bookinglabour',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bookingmaterial',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='bookingmaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additional_settings.material'),
        ),
        migrations.AlterField(
            model_name='bookingmaterial',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtruck',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='bookingtruck',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtruck',
            name='truck_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additional_settings.truck'),
        ),
    ]
