# Generated by Django 5.2.1 on 2026-01-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0011_staffmember'),
        ('bookings', '0002_alter_booking_status_alter_bookinglabour_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglabour',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='additional_settings.staffmember'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_bookings', to='additional_settings.staffmember'),
        ),
    ]
