# Generated by Django 5.2.1 on 2026-01-07 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0012_remove_staffmember_category_and_more'),
        ('bookings', '0003_bookinglabour_staff_member_alter_booking_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_bookings', to='additional_settings.manpower'),
        ),
        migrations.AlterField(
            model_name='bookinglabour',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='additional_settings.manpower'),
        ),
    ]
