# Generated by Django 5.2.1 on 2026-01-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_created_at_alter_booking_updated_at'),
        ('bookings', '0005_remove_booking_start_date_booking_start_time'),
    ]

    operations = [
    ]
