# Generated by Django 5.2.1 on 2026-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_employer_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='employer_agency',
        ),
        migrations.AddField(
            model_name='bookinglabour',
            name='employer_agency',
            field=models.CharField(choices=[('almas', 'Almas Movers'), ('outside', 'Outside Workers')], default='almas', help_text='Agency or employer of the assigned staff', max_length=20),
        ),
    ]
