# Generated by Django 5.2.1 on 2026-01-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_booking_employer_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglabour',
            name='employer_agency',
        ),
    ]
