# Generated by Django 5.2.1 on 2026-01-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_bookinglabour_employer_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglabour',
            name='labour_type',
        ),
    ]
