# Generated by Django 5.2.1 on 2026-01-14 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_bookinglabour_labour_type'),
        ('pricing', '0010_alter_trucktype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtruck',
            name='truck_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.trucktype'),
        ),
    ]
