# Generated by Django 5.2.1 on 2025-11-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additional_settings', '0006_surveyadditionalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('currency', models.CharField(blank=True, default='QAR', max_length=10, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_unit_quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('rate_type', models.CharField(blank=True, choices=[('FIX', 'FIX'), ('VARIABLE', 'VARIABLE')], default='FIX', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_country', models.CharField(blank=True, default='Qatar', max_length=100, null=True)),
                ('pricing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('min_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum volume in CBM (e.g., 0.01)', max_digits=10, null=True)),
                ('max_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum volume in CBM (e.g., 10.00)', max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Price in QAR', max_digits=12, null=True)),
                ('rate_type', models.CharField(blank=True, choices=[('variable', 'Variable (Rate × Volume)'), ('flat', 'Flat Rate')], default='flat', max_length=10, null=True)),
                ('currency', models.CharField(default='QAR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Additional adjustment to the rate', max_digits=12, null=True)),
                ('move_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.movetype')),
            ],
            options={
                'indexes': [models.Index(fields=['pricing_country', 'pricing_city', 'is_active'], name='pricing_pri_pricing_01d481_idx'), models.Index(fields=['move_type', 'is_active'], name='pricing_pri_move_ty_57030b_idx')],
            },
        ),
    ]
