# Generated by Django 5.2.1 on 2025-11-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0006_surveyadditionalservice'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationAdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('per_unit_quantity', models.PositiveIntegerField(default=1)),
                ('rate_type', models.CharField(choices=[('FIX', 'FIX'), ('VARIABLE', 'VARIABLE')], default='FIX', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.currency')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_charges', to='additional_settings.surveyadditionalservice')),
            ],
            options={
                'verbose_name': 'Quotation Additional Charge',
                'verbose_name_plural': 'Quotation Additional Charges',
                'ordering': ['service__name'],
            },
        ),
    ]
