# Generated by Django 5.2.1 on 2025-11-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0006_surveyadditionalservice'),
        ('pricing', '0002_quotationadditionalcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(blank=True, default='QAR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='per_unit_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('FIX', 'FIX'), ('VARIABLE', 'VARIABLE')], default='FIX', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_charges', to='additional_settings.surveyadditionalservice'),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='InclusionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, choices=[('include', 'Include'), ('exclude', 'Exclude')], max_length=10, null=True)),
                ('country', models.CharField(default='Qatar', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Inclusion / Exclusion Item',
                'verbose_name_plural': 'Inclusion / Exclusion Items',
                'indexes': [models.Index(fields=['type'], name='pricing_inc_type_828861_idx'), models.Index(fields=['city'], name='pricing_inc_city_f31910_idx'), models.Index(fields=['is_active'], name='pricing_inc_is_acti_2ad881_idx')],
                'unique_together': {('text', 'type', 'city')},
            },
        ),
    ]
