# Generated by Django 5.2.1 on 2025-11-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_quotationadditionalcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclusionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], max_length=10)),
                ('country', models.CharField(default='Qatar', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inclusion / Exclusion Item',
                'verbose_name_plural': 'Inclusion / Exclusion Items',
                'indexes': [models.Index(fields=['type'], name='pricing_inc_type_828861_idx'), models.Index(fields=['city'], name='pricing_inc_city_f31910_idx'), models.Index(fields=['is_active'], name='pricing_inc_is_acti_2ad881_idx')],
                'unique_together': {('text', 'type', 'city')},
            },
        ),
    ]
