# Generated by Django 5.2.1 on 2025-12-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_inclusionexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='Shown to customer in quote')),
                ('calculation_type', models.CharField(choices=[('free', 'Free (Included in Base Price)'), ('percentage', 'Percentage of Total Quote Value'), ('fixed', 'Fixed Amount'), ('per_item', 'Fixed Amount Per High-Value Item')], default='percentage', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='e.g. 3.50 for 3.5% or 250.00 for QAR 250 fixed', max_digits=10)),
                ('minimum_premium', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum charge even if calculation is lower', max_digits=10)),
                ('maximum_coverage', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount this plan covers (optional)', max_digits=14, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-selected when generating quote')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Customer cannot unselect this')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Plan',
                'verbose_name_plural': 'Insurance Plans',
                'ordering': ['order', 'name'],
            },
        ),
    ]
