# Generated by Django 5.2.1 on 2025-12-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_price_created_at_alter_price_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown to customer in quote', null=True)),
                ('calculation_type', models.CharField(blank=True, choices=[('free', 'Free (Included in Base Price)'), ('percentage', 'Percentage of Total Quote Value'), ('fixed', 'Fixed Amount'), ('per_item', 'Fixed Amount Per High-Value Item')], default='percentage', max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 3.50 for 3.5% or 250.00 for QAR 250 fixed', max_digits=10, null=True)),
                ('minimum_premium', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Minimum charge even if calculation is lower', max_digits=10, null=True)),
                ('maximum_coverage', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount this plan covers (optional)', max_digits=14, null=True)),
                ('is_default', models.BooleanField(blank=True, default=False, help_text='Auto-selected when generating quote', null=True)),
                ('is_mandatory', models.BooleanField(blank=True, default=False, help_text='Customer cannot unselect this', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Display order', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Insurance Plan',
                'verbose_name_plural': 'Insurance Plans',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown in quote to customer', null=True)),
                ('advance_percentage', models.DecimalField(blank=True, decimal_places=2, default=50.0, help_text='e.g. 50.00 = 50% advance', max_digits=5, null=True)),
                ('advance_due_on', models.CharField(blank=True, choices=[('survey', 'Upon Survey Confirmation'), ('packing', 'Before Packing'), ('delivery', 'On Delivery'), ('after_delivery', 'After Delivery (Net 7/15/30)')], default='survey', max_length=20, null=True)),
                ('balance_due_on', models.CharField(blank=True, choices=[('survey', 'Upon Survey Confirmation'), ('packing', 'Before Packing'), ('delivery', 'On Delivery'), ('after_delivery', 'After Delivery (Net 7/15/30)')], default='delivery', max_length=20, null=True)),
                ('is_default', models.BooleanField(blank=True, default=False, help_text='Auto-selected in quote', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField(blank=True, help_text='Full note text shown in quote', null=True)),
                ('category', models.CharField(blank=True, choices=[('general', 'General'), ('packing', 'Packing'), ('delivery', 'Delivery'), ('storage', 'Storage'), ('payment', 'Payment'), ('legal', 'Legal / Terms'), ('custom', 'Custom')], default='general', max_length=20, null=True)),
                ('is_default', models.BooleanField(blank=True, default=False, help_text='Automatically included in every new quote', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Quote Note',
                'verbose_name_plural': 'Quote Notes',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SurveyRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional longer explanation', null=True)),
                ('category', models.CharField(blank=True, choices=[('access', 'Access Issues'), ('packing', 'Packing Related'), ('items', 'Special Items'), ('building', 'Building / Elevator'), ('timing', 'Timing / Scheduling'), ('other', 'Other')], default='other', max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Survey Remark',
                'verbose_name_plural': 'Survey Remarks',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('capacity_cbm', models.DecimalField(blank=True, decimal_places=2, help_text='Volume capacity in cubic meters (CBM)', max_digits=6, null=True)),
                ('capacity_kg', models.PositiveIntegerField(blank=True, help_text='Weight capacity in kilograms', null=True)),
                ('price_per_trip', models.DecimalField(blank=True, decimal_places=2, help_text='Base price per trip in QAR', max_digits=10, null=True)),
                ('length_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-selected in new surveys')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truck Type',
                'verbose_name_plural': 'Truck Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='country',
            field=models.CharField(blank=True, default='Qatar', max_length=100, null=True),
        ),
    ]
