# Generated by Django 5.2.1 on 2025-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_insuranceplan_paymentterm_quotenote_surveyremark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the additional service (e.g., Boom Truck, Curtain Installation)', max_length=200, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Additional Service',
                'verbose_name_plural': 'Additional Services',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, help_text='Auto-selected in new surveys', null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
