# Generated by Django 5.2.1 on 2025-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_insuranceplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='Shown in quote to customer')),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='e.g. 50.00 = 50% advance', max_digits=5)),
                ('advance_due_on', models.CharField(choices=[('survey', 'Upon Survey Confirmation'), ('packing', 'Before Packing'), ('delivery', 'On Delivery'), ('after_delivery', 'After Delivery (Net 7/15/30)')], default='survey', max_length=20)),
                ('balance_due_on', models.CharField(choices=[('survey', 'Upon Survey Confirmation'), ('packing', 'Before Packing'), ('delivery', 'On Delivery'), ('after_delivery', 'After Delivery (Net 7/15/30)')], default='delivery', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-selected in quote')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
                'ordering': ['order', 'name'],
            },
        ),
    ]
