# Generated by Django 5.2.1 on 2025-12-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the additional service (e.g., Boom Truck, Curtain Installation)', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, help_text='Auto-selected in new surveys', null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
