# Generated by Django 5.2.1 on 2025-12-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_paymentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(help_text='Full note text shown in quote')),
                ('category', models.CharField(choices=[('general', 'General'), ('packing', 'Packing'), ('delivery', 'Delivery'), ('storage', 'Storage'), ('payment', 'Payment'), ('legal', 'Legal / Terms'), ('custom', 'Custom')], default='general', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Automatically included in every new quote')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Note',
                'verbose_name_plural': 'Quote Notes',
                'ordering': ['order', 'title'],
            },
        ),
    ]
