# Generated by Django 5.2.1 on 2026-01-01 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0007_item_height_item_length_item_volume_item_weight_and_more'),
        ('pricing', '0005_service_alter_trucktype_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_charges', to='additional_settings.surveyadditionalservice'),
        ),
    ]
