# Generated by Django 5.2.1 on 2025-12-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_quotenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity_cbm', models.DecimalField(decimal_places=2, help_text='Volume capacity in cubic meters (CBM)', max_digits=6)),
                ('capacity_kg', models.PositiveIntegerField(help_text='Weight capacity in kilograms')),
                ('price_per_trip', models.DecimalField(decimal_places=2, help_text='Base price per trip in QAR', max_digits=10)),
                ('length_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-selected in new surveys')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truck Type',
                'verbose_name_plural': 'Truck Types',
                'ordering': ['order', 'name'],
            },
        ),
    ]
