# Generated by Django 5.2.1 on 2026-01-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_quotationadditionalcharge_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trucktype',
            name='height_meters',
        ),
        migrations.RemoveField(
            model_name='trucktype',
            name='length_meters',
        ),
        migrations.RemoveField(
            model_name='trucktype',
            name='width_meters',
        ),
    ]
