# Generated by Django 5.2.1 on 2026-01-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_remove_trucktype_height_meters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotenote',
            options={'ordering': ['order'], 'verbose_name': 'Quote Note', 'verbose_name_plural': 'Quote Notes'},
        ),
        migrations.RemoveField(
            model_name='quotenote',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quotenote',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='quotenote',
            name='title',
        ),
    ]
