# Generated by Django 5.2.1 on 2025-12-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_trucktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional longer explanation')),
                ('category', models.CharField(choices=[('access', 'Access Issues'), ('packing', 'Packing Related'), ('items', 'Special Items'), ('building', 'Building / Elevator'), ('timing', 'Timing / Scheduling'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Survey Remark',
                'verbose_name_plural': 'Survey Remarks',
                'ordering': ['order', 'title'],
            },
        ),
    ]
