# Generated by Django 5.2.1 on 2025-12-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0007_item_height_item_length_item_volume_item_weight_and_more'),
        ('pricing', '0008_surveyremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='country',
            field=models.CharField(blank=True, default='Qatar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='type',
            field=models.CharField(blank=True, choices=[('include', 'Include'), ('exclude', 'Exclude')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='calculation_type',
            field=models.CharField(blank=True, choices=[('free', 'Free (Included in Base Price)'), ('percentage', 'Percentage of Total Quote Value'), ('fixed', 'Fixed Amount'), ('per_item', 'Fixed Amount Per High-Value Item')], default='percentage', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='description',
            field=models.TextField(blank=True, help_text='Shown to customer in quote', null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, help_text='Auto-selected when generating quote', null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='is_mandatory',
            field=models.BooleanField(blank=True, default=False, help_text='Customer cannot unselect this', null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='minimum_premium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Minimum charge even if calculation is lower', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 3.50 for 3.5% or 250.00 for QAR 250 fixed', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='advance_due_on',
            field=models.CharField(blank=True, choices=[('survey', 'Upon Survey Confirmation'), ('packing', 'Before Packing'), ('delivery', 'On Delivery'), ('after_delivery', 'After Delivery (Net 7/15/30)')], default='survey', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='advance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, help_text='e.g. 50.00 = 50% advance', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='balance_due_on',
            field=models.CharField(blank=True, choices=[('survey', 'Upon Survey Confirmation'), ('packing', 'Before Packing'), ('delivery', 'On Delivery'), ('after_delivery', 'After Delivery (Net 7/15/30)')], default='delivery', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='description',
            field=models.TextField(blank=True, help_text='Shown in quote to customer', null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, help_text='Auto-selected in quote', null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(blank=True, default='QAR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='per_unit_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('FIX', 'FIX'), ('VARIABLE', 'VARIABLE')], default='FIX', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_charges', to='additional_settings.surveyadditionalservice'),
        ),
        migrations.AlterField(
            model_name='quotationadditionalcharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotenote',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('packing', 'Packing'), ('delivery', 'Delivery'), ('storage', 'Storage'), ('payment', 'Payment'), ('legal', 'Legal / Terms'), ('custom', 'Custom')], default='general', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotenote',
            name='content',
            field=models.TextField(blank=True, help_text='Full note text shown in quote', null=True),
        ),
        migrations.AlterField(
            model_name='quotenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotenote',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotenote',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, help_text='Automatically included in every new quote', null=True),
        ),
        migrations.AlterField(
            model_name='quotenote',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quotenote',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quotenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyremark',
            name='category',
            field=models.CharField(blank=True, choices=[('access', 'Access Issues'), ('packing', 'Packing Related'), ('items', 'Special Items'), ('building', 'Building / Elevator'), ('timing', 'Timing / Scheduling'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyremark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyremark',
            name='description',
            field=models.TextField(blank=True, help_text='Optional longer explanation', null=True),
        ),
        migrations.AlterField(
            model_name='surveyremark',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyremark',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyremark',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyremark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='capacity_cbm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume capacity in cubic meters (CBM)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='capacity_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Weight capacity in kilograms', null=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='price_per_trip',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price per trip in QAR', max_digits=10, null=True),
        ),
    ]
