# Generated by Django 5.2.1 on 2026-01-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_alter_quotenote_options_remove_quotenote_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyremark',
            options={'ordering': ['order'], 'verbose_name': 'Survey Remark', 'verbose_name_plural': 'Survey Remarks'},
        ),
        migrations.RemoveField(
            model_name='surveyremark',
            name='category',
        ),
        migrations.RemoveField(
            model_name='surveyremark',
            name='title',
        ),
    ]
