# Generated by Django 5.2.1 on 2026-01-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_alter_surveyremark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucktype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
