# Generated by Django 5.2.1 on 2026-01-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_alter_trucktype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyremark',
            options={'verbose_name': 'Survey Remark', 'verbose_name_plural': 'Survey Remarks'},
        ),
        migrations.RemoveField(
            model_name='surveyremark',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='surveyremark',
            name='order',
        ),
    ]
