# Generated by Django 5.2.1 on 2026-01-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_alter_surveyremark_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyRemark',
        ),
    ]
