# Generated by Django 5.2.1 on 2025-11-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_role_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
