# Generated by Django 5.2.1 on 2025-11-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_customuser_otp_customuser_otp_expiry'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
