# Generated by Django 5.2.1 on 2025-11-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_enquiry_contact_status_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='recaptchaToken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='refererUrl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='submittedUrl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
