# Generated by Django 5.2.1 on 2025-11-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0003_team_phone'),
        ('contact', '0004_enquiry_contact_status_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to='additional_settings.team'),
        ),
    ]
