# Generated by Django 5.2.1 on 2025-11-04 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_enquiry_contact_enq_created_b6ecb0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact_status',
            field=models.CharField(blank=True, choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact_status_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='reached_out_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='reached_out_whatsapp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='survey_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='refererUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['assigned_user'], name='contact_enq_assigne_fc4384_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['contact_status'], name='contact_enq_contact_2116b9_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['survey_date'], name='contact_enq_survey__369145_idx'),
        ),
    ]
