# Generated by Django 5.2.1 on 2025-11-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_enquiry_assigned_user_enquiry_contact_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='refererUrl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='submittedUrl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
