# Generated by Django 5.2.1 on 2025-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_enquiry_refererurl_alter_enquiry_submittedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='recaptchaToken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
