# Generated by Django 5.2.1 on 2025-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_enquiry_recaptchatoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='refererUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='submittedUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
