# Generated by Django 5.2.1 on 2025-12-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_enquiry_refererurl_alter_enquiry_submittedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='refererUrl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='submittedUrl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
