# Generated by Django 5.2.1 on 2026-01-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_enquiry_refererurl_alter_enquiry_submittedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='refererUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='submittedUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
