# Generated by Django 5.2.1 on 2025-12-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_enquiry_refererurl_alter_enquiry_submittedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='refererUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='submittedUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
