# Generated by Django 5.2.1 on 2025-11-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_enquiry_recaptchatoken'),
        ('survey', '0002_alter_survey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='signature',
            field=models.FileField(blank=True, help_text='Customer signature file', null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='contact.enquiry'),
        ),
    ]
