# Generated by Django 5.2.1 on 2025-12-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_article_survey_arti_survey__e52ca9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
