# Generated by Django 5.2.1 on 2025-12-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_article_survey_arti_survey__e52ca9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='crate_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
