# Generated by Django 5.2.1 on 2025-12-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_article_crate_required_article_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_flagged',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
