# Generated by Django 5.2.1 on 2025-12-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_article_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='crate_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
