# Generated by Django 5.2.1 on 2026-01-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0007_item_height_item_length_item_volume_item_weight_and_more'),
        ('survey', '0007_alter_article_is_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='additional_services',
        ),
        migrations.CreateModel(
            name='SurveyAdditionalServiceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additional_settings.surveyadditionalservice')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_service_selections', to='survey.survey')),
            ],
            options={
                'unique_together': {('survey', 'service')},
            },
        ),
    ]
