# Generated by Django 5.2.1 on 2025-10-08 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0001_initial'),
        ('survey', '0007_alter_article_created_at_alter_pet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='customer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='additional_settings.customertype'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='additional_settings.servicetype'),
        ),
    ]
