# Generated by Django 5.2.1 on 2025-10-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_survey_customer_type_alter_survey_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mobile_country_code',
        ),
    ]
