# Generated by Django 5.2.1 on 2026-01-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_survey_additional_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
