# Generated by Django 5.2.1 on 2026-01-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_remove_survey_additional_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='additional_services',
        ),
    ]
