# Generated by Django 5.2.1 on 2026-01-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='origin_gps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
