# Generated by Django 5.2.1 on 2025-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_rename_first_name_survey_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
