# Generated by Django 5.2.1 on 2025-10-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_survey_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
