# Generated by Django 5.2.1 on 2026-01-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_survey_origin_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
