# Generated by Django 5.2.1 on 2025-10-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_rename_mobile_number_survey_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='calculated_volume',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Auto-calculated volume (L×W×H/1000000)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True),
        ),
    ]
