# Generated by Django 5.2.1 on 2025-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_article_calculated_volume_article_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='calculated_volume',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Auto-calculated volume (L×W×H/1000000)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Height in cm', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Length in cm', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Width in cm', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
