# Generated by Django 5.2.1 on 2026-01-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_remove_article_image_article_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at']},
        ),
    ]
