# Generated by Django 5.2.1 on 2025-11-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_enquiry_recaptchatoken_and_more'),
        ('survey', '0014_alter_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='enquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='contact.enquiry'),
        ),
    ]
