# Generated by Django 5.2.1 on 2025-11-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_alter_survey_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='survey',
            name='signature',
            field=models.FileField(blank=True, help_text='Customer signature file', null=True, upload_to='signatures/'),
        ),
    ]
