# Generated by Django 5.2.1 on 2025-11-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_remove_survey_updated_at_survey_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
