# Generated by Django 5.2.1 on 2025-11-19 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0006_surveyadditionalservice'),
        ('survey', '0019_alter_survey_created_at_alter_survey_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySelectedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additional_settings.surveyadditionalservice')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='survey.survey')),
            ],
            options={
                'indexes': [models.Index(fields=['survey'], name='survey_surv_survey__e96670_idx'), models.Index(fields=['service'], name='survey_surv_service_ec5b33_idx')],
                'unique_together': {('survey', 'service')},
            },
        ),
    ]
