# Generated by Django 5.2.1 on 2025-11-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_surveyselectedservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveySelectedService',
        ),
    ]
