# Generated by Django 5.2.1 on 2025-11-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_delete_surveyselectedservice'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='survey_arti_survey__e52ca9_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='survey_arti_created_4b4691_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='survey_arti_room_id_ddab24_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='survey_vehi_survey__0a3f5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='survey_vehi_created_358dc6_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='article',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='cost_together_pet',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='cost_together_vehicle',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='include_pet',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='include_vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transport_mode',
        ),
        migrations.AlterField(
            model_name='article',
            name='calculated_volume',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
