# Generated by Django 5.2.1 on 2025-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0010_alter_surveyadditionalservice_options'),
        ('survey', '0022_remove_article_survey_arti_survey__e52ca9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='additional_settings.surveyadditionalservice'),
        ),
    ]
