# Generated by Django 5.2.1 on 2025-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_volume', models.DecimalField(decimal_places=2, help_text='Minimum volume in CBM (e.g., 0.01)', max_digits=10)),
                ('max_volume', models.DecimalField(decimal_places=2, help_text='Maximum volume in CBM (e.g., 10.00)', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Price in QAR', max_digits=12)),
                ('rate_type', models.CharField(choices=[('variable', 'Variable (Rate × Volume)'), ('flat', 'Flat Rate')], default='flat', max_length=10)),
                ('currency', models.CharField(default='QAR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Range',
                'verbose_name_plural': 'Price Ranges',
                'ordering': ['min_volume'],
                'unique_together': {('min_volume', 'max_volume')},
            },
        ),
    ]
