# Generated by Django 5.2.1 on 2025-11-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0005_movetype_tarifftype'),
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.hub'),
        ),
        migrations.AddField(
            model_name='price',
            name='move_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_settings.movetype'),
        ),
    ]
