# Generated by Django 5.2.1 on 2025-11-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_price_hub_price_move_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='adjustment_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional adjustment to the rate', max_digits=12),
        ),
    ]
