# Generated by Django 5.2.1 on 2025-11-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_price_adjustment_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
    ]
