# Generated by Django 5.2.1 on 2025-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_alter_price_options_alter_price_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('currency', models.CharField(default='QAR', max_length=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('per_unit_quantity', models.PositiveIntegerField(default=1)),
                ('rate_type', models.CharField(choices=[('FIX', 'FIX'), ('VARIABLE', 'VARIABLE')], default='FIX', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('service_name',)},
            },
        ),
    ]
