# Generated by Django 5.2.1 on 2025-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_additionalservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'ordering': ['service_name']},
        ),
        migrations.AlterUniqueTogether(
            name='additionalservice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='service_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
