# Generated by Django 5.2.1 on 2025-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_alter_additionalservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='currency',
            field=models.CharField(blank=True, default='QAR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='per_unit_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('FIX', 'FIX'), ('VARIABLE', 'VARIABLE')], default='FIX', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='service_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='adjustment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Additional adjustment to the rate', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='max_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum volume in CBM (e.g., 10.00)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='min_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum volume in CBM (e.g., 0.01)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in QAR', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('variable', 'Variable (Rate × Volume)'), ('flat', 'Flat Rate')], default='flat', max_length=10, null=True),
        ),
    ]
