# Generated by Django 5.2.1 on 2025-10-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in meters', max_digits=10, null=True),
        ),
    ]
