# Generated by Django 5.2.1 on 2025-10-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0002_room_height_room_length_room_width'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='room',
            name='height',
        ),
        migrations.RemoveField(
            model_name='room',
            name='length',
        ),
        migrations.RemoveField(
            model_name='room',
            name='width',
        ),
    ]
