# Generated by Django 5.2.1 on 2025-11-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0002_hub_team_alter_currency_name_alter_customertype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
