# Generated by Django 5.2.1 on 2025-11-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0003_team_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tariffrange',
            name='tariff',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='type',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='code',
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
        migrations.DeleteModel(
            name='TariffRange',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
