# Generated by Django 5.2.1 on 2025-11-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0003_alter_tariff_unique_together_remove_tariff_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='updated_at',
        ),
    ]
