# Generated by Django 5.2.1 on 2025-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0004_remove_hub_created_at_remove_hub_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
