# Generated by Django 5.2.1 on 2025-11-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0004_alter_tariff_unique_together_remove_tariff_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
