# Generated by Django 5.2.1 on 2025-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0005_item_calculated_volume_alter_item_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='calculated_volume',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Auto-calculated volume (L×W×H/1000000)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Height in cm', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Length in cm', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Volume in m³', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Weight in kg', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Width in cm', max_digits=20, null=True),
        ),
    ]
