# Generated by Django 5.2.1 on 2025-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0005_movetype_tarifftype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('has_quantity', models.BooleanField(default=False, help_text='If true, quantity field will be shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Survey Additional Service',
                'verbose_name_plural': 'Survey Additional Services',
                'ordering': ['name'],
            },
        ),
    ]
