# Generated by Django 5.2.1 on 2025-11-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0005_movetype_tarifftype_hub_created_at_hub_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
