# Generated by Django 5.2.1 on 2025-12-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0006_surveyadditionalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='in m³ (auto-calculated)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in kg (estimated)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=10, null=True),
        ),
    ]
