# Generated by Django 5.2.1 on 2025-11-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0006_surveyadditionalservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyadditionalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyadditionalservice',
            name='has_quantity',
            field=models.BooleanField(blank=True, default=False, help_text='If true, quantity field will be shown', null=True),
        ),
        migrations.AlterField(
            model_name='surveyadditionalservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
