# Generated by Django 5.2.1 on 2025-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0007_alter_surveyadditionalservice_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyadditionalservice',
            name='has_quantity',
        ),
        migrations.AddField(
            model_name='surveyadditionalservice',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
