# Generated by Django 5.2.1 on 2026-01-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0008_labour_material_truck_hub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyadditionalservice',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
