# Generated by Django 5.2.1 on 2025-11-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0008_remove_surveyadditionalservice_has_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyadditionalservice',
            name='quantity',
        ),
    ]
