# Generated by Django 5.2.1 on 2025-11-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0009_remove_surveyadditionalservice_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyadditionalservice',
            options={},
        ),
    ]
