# Generated by Django 5.2.1 on 2026-01-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0011_staffmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='category',
        ),
        migrations.RemoveField(
            model_name='manpower',
            name='description',
        ),
        migrations.AddField(
            model_name='manpower',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manpower',
            name='employer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manpower',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manpower',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
