# Generated by Django 5.2.1 on 2026-01-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0012_remove_staffmember_category_and_more'),
        ('bookings', '0004_alter_booking_supervisor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
