# Generated by Django 5.2.1 on 2026-01-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0014_alter_manpower_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpower',
            name='employer',
            field=models.CharField(blank=True, choices=[('almas', 'Almas Movers'), ('outside', 'Outside Workers')], default=None, help_text='Select the employer or agency for this manpower', max_length=20, null=True),
        ),
    ]
