# Generated by Django 5.2.1 on 2026-01-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0015_alter_manpower_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpower',
            name='employer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
