# Generated by Django 5.2.1 on 2026-01-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0016_alter_manpower_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpower',
            name='employer',
            field=models.CharField(blank=True, choices=[('Almas Movers', 'Almas Movers'), ('Outside Workers', 'Outside Workers')], max_length=200, null=True),
        ),
    ]
