# Generated by Django 5.2.1 on 2026-01-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0018_insurance_paymentterm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
    ]
