# Generated by Django 5.2.1 on 2026-01-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0019_delete_insurance_delete_paymentterm'),
        ('bookings', '0011_alter_bookingtruck_truck_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
