# Generated by Django 5.2.1 on 2026-01-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0020_delete_truck'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
