# Generated by Django 5.2.1 on 2025-11-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='excluded_services',
            field=models.JSONField(blank=True, default=list, help_text="List of excluded services (e.g., ['Insurance', 'Storage'])"),
        ),
        migrations.AddField(
            model_name='quotation',
            name='included_services',
            field=models.JSONField(blank=True, default=list, help_text="List of included services (e.g., ['Packing Service', 'Loading'])"),
        ),
    ]
