# Generated by Django 5.2.1 on 2025-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotation_pricing_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='serial_no',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='excluded_services',
            field=models.JSONField(blank=True, default=list, help_text='List of excluded services IDs', null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='included_services',
            field=models.JSONField(blank=True, default=list, help_text='List of included services IDs', null=True),
        ),
    ]
