# Generated by Django 5.2.1 on 2025-11-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotation_excluded_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pricing_mode',
            field=models.CharField(choices=[('variable', 'Variable'), ('fixed', 'Fixed')], default='variable', help_text='How the amount was calculated', max_length=20),
        ),
    ]
