# Generated by Django 5.2.1 on 2025-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotation_pricing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='excluded_services',
            field=models.JSONField(blank=True, default=list, help_text="List of excluded services (e.g., ['Insurance', 'Storage'])", null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='included_services',
            field=models.JSONField(blank=True, default=list, help_text="List of included services (e.g., ['Packing Service', 'Loading'])", null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pricing_mode',
            field=models.CharField(blank=True, choices=[('variable', 'Variable'), ('fixed', 'Fixed')], default='variable', help_text='How the amount was calculated', max_length=20, null=True),
        ),
    ]
