# Generated by Django 5.2.1 on 2025-12-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_remove_quotation_serial_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='selected_services',
            field=models.JSONField(blank=True, default=list, help_text='List of selected general services (from /services/) IDs chosen by user with round buttons', null=True),
        ),
    ]
