# Generated by Django 5.2.1 on 2026-01-02 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation_selected_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining amount to pay (final_amount - advance)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount amount in the quotation currency', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='quotation',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount after discount (amount - discount)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
