# Generated by Django 5.2.1 on 2026-01-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_quotation_balance_quotation_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='quotation_signatures/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signature_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
