# Generated by Django 5.2.1 on 2026-01-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_quotation_signature_quotation_signature_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_charges',
            field=models.JSONField(blank=True, default=list, help_text='Detailed additional charges with price and quantity', null=True),
        ),
    ]
