# Generated by Django 5.2.1 on 2026-01-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_quotation_additional_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='remarks',
            field=models.JSONField(blank=True, default=list, help_text='List of selected SurveyRemark IDs', null=True),
        ),
    ]
