# Generated by Django 5.2.1 on 2026-01-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_quotation_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Optional longer explanation', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Quotation Remark',
                'verbose_name_plural': 'Quotation Remarks',
            },
        ),
    ]
